### PR TITLE
Fix callback details for array changes

### LINKED ISSUE #24: Array change within object loses callback details
test.ts
```ts
const onChange = require("on-change");

let i: number = 0;
const obj = {
    a: "",
    b: ["a", "b", "c"]
};

const watchedSettings = onChange(obj, function(
    path: any,
    value: any,
    previousValue: any
) {
    console.log("Object changed:", ++i);
    console.log("this:", this);
    console.log("path:", path);
    console.log("value:", value);
    console.log("previousValue:", previousValue);
});

watchedSettings.a = "test";
watchedSettings.b.push("d");
```

The output from this is:

```
~>tsc -p . && node test.js
Object changed: 1
this: { a: 'test', b: [ 'a', 'b', 'c' ] }
path: a
value: test
previousValue:
Object changed: 2
this: undefined
path: undefined
value: undefined
previousValue: undefined
```

The change to "a" works, but the update to the array "b" in the second returns "undefined" for all fields in the callback.  It detected the change, but lost all of the details.

node: 11.12.0
on-change: 1.2.0
typescript: 3.4.1

### PR DESCRIPTION
**Pull request by DarrenPaulWright**
Fixes #24. This branch includes the changes in #29.

I realized that we don't need to clone everything, only the things that get modified, and we already have the previous values. So no more clone option, or any other option.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?

**Comment by DarrenPaulWright** [comment]
Don't merge yet, I think I found a problem.

**Comment by DarrenPaulWright** [comment]
Ok, I think it's fine. The problem was with the benchmarks.

**Comment by sindresorhus** [comment]
Weird, this passed locally for me, but on Travis it fails: https://travis-ci.org/sindresorhus/on-change/builds/539069267

**Pull request merged**
