### PR TITLE
Don't proxy `RegExp` and `Number`, detect changes to `Date`

### LINKED ISSUE #25: Error / invalid behavior when using dates
Failing test (in main):

```javascript
// Support dates
object.bar.a.c[2] = new Date(1546300800000);
t.deepEqual(object.bar.a.c[2], new Date(1546300800000));
t.is(object.bar.a.c[2].valueOf(), 1546300800000);
t.is(callCount, 9);
```

```
 1 test failed

  main

  /code/github/on-change/index.js:125

   124:
   125:         const result = Reflect.apply(target, thisArg, argumentsList);
   126:

  Error thrown in test:

  TypeError {
    message: 'this is not a Date object.',
  }

  Object.apply (index.js:125:28)
  unboxComplex (node_modules/concordance/lib/describe.js:78:27)
  describeComplex (node_modules/concordance/lib/describe.js:112:17)
  curriedComplex (node_modules/concordance/lib/describe.js:143:12)
  describe (node_modules/concordance/lib/describe.js:170:10)
  Object.compare (node_modules/concordance/lib/compare.js:98:12)
  deepEqual (test.js:65:4)
```

### PR DESCRIPTION
**Pull request by DarrenPaulWright**
Fixes #25. This fix still returns a proxied date, so comparing a proxied date to the original date will still return false, but calling the methods on the proxied date should work as expected now.

### CODE REVIEW

**Comment by sindresorhus** [comment]
@DarrenPaulWright Thanks for all the high-quality PRs. Would you be interested in being added as a maintainer on this project?

**Comment by DarrenPaulWright** [comment]
@sindresorhus that sounds great!

**Comment by sindresorhus** [comment]
Awesome :)

**Comment by SneakyMax** [comment]
Thanks @DarrenPaulWright!

**Pull request merged**
