### PR TITLE
Add benchmark

### LINKED ISSUE #3: Performance
I am curious about the performance of this vs. calling `save` explicitly. Is there a benchmark?

### PR DESCRIPTION
**Pull request by glundgren93**
12,304 op/s » onChange
          12,530 op/s » save

(Using Node.js 8.9.0)

Closes #3

### CODE REVIEW

**Comment by sindresorhus** [comment]
Make sure `npm test` succeeds locally. You can run `npx xo --fix` to fix most lint issues.

**Comment by glundgren93** [comment]
The test say that suite, set and bench are not defined. How can I fix this?

**Comment by glundgren93** [comment]
Fixed it! With new changes, the benchmark is:
           9,917 op/s » onChange
          13,350 op/s » save

**Comment by glundgren93** [comment]
Is something wrong or is something missing?

**Comment by sindresorhus** [comment]
Looks good. Thank you! :)

**Pull request merged**
