### PR TITLE
Fix typed array update

### PR DESCRIPTION
**Pull request by hpx7**
Fixes https://github.com/sindresorhus/on-change/issues/91

### CODE REVIEW

**Comment by hpx7** [comment]
@DarrenPaulWright I'm not able to figure out why the tests are failing, any ideas?

**Comment by sindresorhus** [comment]
Can you add a test?

**Comment by sindresorhus** [comment]
> I'm not able to figure out why the tests are failing, any ideas?

Rebase from `main` branch. It should be fixed there.

**Comment by sindresorhus** [comment]
> Can you add a test?

^

**Comment by hpx7** [comment]
Thanks for merging! Would love to get this in a release when you have the chance to cut one

**Comment by hpx7** [comment]
@DarrenPaulWright or @sindresorhus would you be able to cut a release with this patch?

**Comment by hpx7** [comment]
@DarrenPaulWright @sindresorhus don't want to bother you but just pinging one last time to see if you'd be able to cut a release with this PR. I can also just publish my fork to npm if that's preferable

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/on-change/releases/tag/v4.0.1

**Comment by hpx7** [comment]
Thank you!

**Pull request merged**
