### PR TITLE
Path as array of props instead of dot-notation string

### LINKED ISSUE #44: Path should be an array
Path arg should be an array, since prop name could contain `.`

### PR DESCRIPTION
**Pull request by qwelias**
fixes #44

### CODE REVIEW

**Comment by DarrenPaulWright** [comment]
Try running the benchmarks before and after this change. Pay attention particularly to nested read, object write, and array write in the first two suites where they are taking two to three times as long to run. 

The problem is Array.concat. Try the following and re-run the benchmarks: 
```js
const concatPath = (path = [], prop) => {
	if (prop === null || prop === undefined) {
		return path;
	}

	const output = [...path];
	output.push(prop);

	return output;
};
```

I still want to keep the previous string path as the default behavior, so please add an option to opt-in to getting the path as an array.

**Comment by qwelias** [comment]
Agree with concern regarding `concat`, fixed. But interestingly on node12:
- with `Array#push`: `npm run bench  100.03s user 1.71s system 94% cpu 1:47.25 total`
- with `Array#concat`: `npm run bench  99.01s user 1.59s system 94% cpu 1:46.31 total`
- original: `npm run bench  95.53s user 1.73s system 94% cpu 1:43.16 total`

I guess V8 optimizations really kick in.

Not making array path optional tho, as I think it's inherently wrong.
`walkPath` will bug out if:
- props have `.`
- `ignoreSymbols == false` and path contains a symbol

**Comment by qwelias** [comment]
Nvm my notes regarding performance, `matcha` is broken on node12.

**Comment by SReject** [comment]
> Not making array path optional tho, as I think it's inherently wrong.

While I agree with the statement in general, this project was already published to npm with the feature of path being a string.

So either the main version number in package.json needs bumped or you can alter the handleChange function to

```js
if (!inApply) {

    // if path should be represented as array
    if (options.pathAsArray) {
        path = concatPath(path, property);

    // otherwise convert the path array to a dot-notated string; escape dots in property names
    } else {
        let pathAsString = '';
        path.forEach(property => {
            if (property.toString) {
                if (pathAsString) {
                    pathAsString += '.';
                }
                pathAsString += property.toString().replace(/\./g, "\\.");
            }
        });

        if (property.toString) {
            if (pathAsString) {
                pathAsString += '.';
            }
            pathAsString += property.toString().replace(/\./g, "\\.");
        }

        path = pathAsString;
    }

    onChange(path, value, previous);
    return;
}
```

**Comment by qwelias** [comment]
@SReject Not opposed to major bump btw.
Also feel free to branch off of my changes and submit another PR if you want to build on top of it :)

**Comment by SReject** [comment]
@qwelias I'm not against a major bump either. Just figured I'd spotlight that side of the issue in case it was overlooked.

**Comment by DarrenPaulWright** [comment]
An option "pathAsArray" is being added in #52

**Pull request closed without merging**
